Sackmesser Organization Export Utility

diff --git a/tools/apigee-sackmesser/bin/sackmesser b/tools/apigee-sackmesser/bin/sackmesser
--- a/tools/apigee-sackmesser/bin/sackmesser
+++ b/tools/apigee-sackmesser/bin/sackmesser
@@ -17,12 +17,111 @@
 set -e
 
 SACKMESSER_ROOT=$( (cd "$(dirname "$0")" && cd .. && pwd ))
+source "$SACKMESSER_ROOT/lib/logutils.sh"
 
-CMD_TYPE=$1
+CMD_TYPE="$1"
+shift 1
 
-if [ -z "$CMD_TYPE" ];then
-    echo "provide a command"
-else
-    echo "$CMD_TYPE"
-    bash "$SACKMESSER_ROOT"/cmd/"$CMD_TYPE"/"$CMD_TYPE".sh "${@:2}"
+print_usage() {
+    cat << EOF
+usage: sackmesser COMMAND -e ENV -o ORG [--googleapi | --apigeeapi] [-t TOKEN | -u USER -p PASSWORD] [options]
+
+Apigee Sackmesser utility.
+
+Commands:
+deploy
+list
+export
+
+Options:
+--googleapi (default), use apigee.googleapi.com (for X, hybrid)
+--apigeeapi, use api.enterprise.apigee.com (for Edge)
+-b,--base-path, overrides the default base path for the API proxy
+-d,--directory, path to the apiproxy or shared flow bundle to be deployed
+-e,--environment, Apigee environment name
+-g,--github, Link to proxy or shared flow bundle on github
+-n,--name, Overrides the default API proxy or shared flow name
+-o,--organization, Apigee organization name
+-u,--username, Apigee User Name (Edge only)
+-p,--password, Apigee User Password (Edge only)
+-m,--mfa, Apigee MFA code (Edge only)
+-t,--token, GCP token (X,hybrid only) or OAuth2 token (Edge)
+-h,--hostname, publicly reachable hostname for the environment
+--description, Human friendly proxy or shared flow description
+--debug, show verbose debug output
+EOF
+}
+
+if [ "$CMD_TYPE" = "--help" ]; then
+    print_usage
+    exit 0
+elif [ -z "$CMD_TYPE" ] || [ ! -f "$SACKMESSER_ROOT"/cmd/"$CMD_TYPE"/"$CMD_TYPE".sh ];then
+    logerror "Please provide a valid command"
+    exit 1
 fi
+
+posArgs=()
+
+while [ "$#" -gt 0 ]; do
+  case "$1" in
+    -b) export base_path="$2"; shift 2;;
+    -d) export directory="$2"; shift 2;;
+    -e) export environment="$2"; shift 2;;
+    -g) export url="$2"; shift 2;;
+    -m) export mfa="$2"; shift 2;;
+    -n) export bundle_name="$2"; shift 2;;
+    -o) export organization="$2"; shift 2;;
+    -p) export password="$2"; shift 2;;
+    -t) export token="$2"; shift 2;;
+    -u) export username="$2"; shift 2;;
+    -h) export hostname="$2"; shift 2;;
+
+    --directory) export directory="${1}"; shift 2;;
+    --github) export url="${1}"; shift 2;;
+    --token) export token="${1}"; shift 2;;
+    --mfa) export mfa="${1}"; shift 2;;
+    --name) export bundle_name="${1}"; shift 2;;
+    --base-path) export base-path="${1}"; shift 2;;
+    --username) export username="${1}"; shift 2;;
+    --password) export password="${1}"; shift 2;;
+    --environment) export environment="${1}"; shift 2;;
+    --organization) export organization="${1}"; shift 2;;
+    --hostname) export hostname="${1}"; shift 2;;
+    --description) export description="${1}"; shift 2;;
+    --debug) export debug="T"; shift 1;;
+
+    --apigeeapi) export apiversion="apigee"; shift 1;;
+    --googleapi) export apiversion="google"; shift 1;;
+
+    -*) echo "[FATAL] unknown option: $1" >&2; exit 1;;
+    *) posArgs+=("$1"); shift 1;;
+  esac
+done
+
+if [[ -z "$apiversion" ]]; then
+    logdebug "using default API version: Google API (apigee.googleapi.com)"
+    logdebug "for Apigee Edge (api.enterprise.apigee.com) please specify --apigeeapi"
+    export apiversion="google"
+fi
+
+
+
+if [ "$apiversion" = "google" ];then
+    export token=${token:-$APIGEE_TOKEN}
+    export organization=${organization:-$APIGEE_X_ORG}
+    export environment=${environment:-$APIGEE_X_ENV}
+    export hostname=${hostname:-$APIGEE_X_HOSTNAME}
+else
+    export password=${password:-$APIGEE_PASS}
+    export username=${username:-$APIGEE_USER}
+    export organization=${organization:-$APIGEE_ORG}
+    export environment=${environment:-$APIGEE_ENV}
+fi
+
+if [[ -z "$token" && (-z "$username"  || -z "$password") ]]; then
+    echo "[FATAL] required either -t (OAuth2 or GCP access token) or -u and -p (Edge username and password)"
+    exit 1
+fi
+
+logdebug "Sackmesser command: $CMD_TYPE"
+"$SACKMESSER_ROOT"/cmd/"$CMD_TYPE"/"$CMD_TYPE".sh "${posArgs[@]}"
