simplify cloud build steps

diff --git a/tools/pipeline-runner/cloudbuild.yaml b/tools/pipeline-runner/cloudbuild.yaml
--- a/tools/pipeline-runner/cloudbuild.yaml
+++ b/tools/pipeline-runner/cloudbuild.yaml
@@ -16,18 +16,17 @@
 steps:
   - name: 'gcr.io/cloud-builders/gcloud'
     id: 'Turnstyle DevRel Pipeline'
-    entrypoint: 'bash'
-    args:
-      - '-c'
-      - |
-        if [ "$(gcloud builds list --ongoing --format='value(id)' | wc  -l | xargs)" -gt "1" ]; then
-          echo "Pipeline is already running";
-          exit -1;
-        fi
+    script: |
+      #!/usr/bin/env bash
+      if [ "$(gcloud builds list --ongoing --format='value(id)' | wc  -l | xargs)" -gt "1" ]; then
+        echo "Pipeline is already running";
+        exit -1;
+      fi
   - name: 'gcr.io/cloud-builders/docker'
     id: 'Pull Image Cache'
-    entrypoint: 'bash'
-    args: ['-c', 'docker pull gcr.io/$PROJECT_ID/devrel-pipeline:latest || exit 0']
+    script: |
+      #!/usr/bin/env bash
+      docker pull gcr.io/$PROJECT_ID/devrel-pipeline:latest || exit 0
   - name: 'gcr.io/cloud-builders/docker'
     id: 'Build Image'
     args:
@@ -41,52 +40,46 @@ steps:
       - './tools/pipeline-runner'
   - name: 'gcr.io/$PROJECT_ID/devrel-pipeline:latest'
     id: 'Cleanup Org'
-    entrypoint: "bash"
-    args:
-      - "-c"
-      - |-
-        if [ "$_CLEAN_ORG" = "true" ]; then
-          APIGEE_TOKEN=$(gcloud auth print-access-token)
-          PATH=$$PATH:"$$PWD/tools/apigee-sackmesser/bin"
-          sackmesser clean all --googleapi -t "$$APIGEE_TOKEN" -o "$_APIGEE_X_ORG" --quiet
-          sackmesser clean all --apigeeapi -u "$$APIGEE_USER" -p "$$APIGEE_PASS" -o "$_APIGEE_ORG" --quiet
-        fi
-    env:
-      - 'APIGEE_ORG=$_APIGEE_ORG'
-      - 'APIGEE_X_ORG=$_APIGEE_X_ORG'
+    script: |
+      #!/usr/bin/env bash
+      if [ "$_CLEAN_ORG" = "true" ]; then
+        APIGEE_TOKEN=$(gcloud auth print-access-token)
+        PATH=$$PATH:"$$PWD/tools/apigee-sackmesser/bin"
+        sackmesser clean all --googleapi -t "$$APIGEE_TOKEN" -o "$_APIGEE_X_ORG" --quiet
+        sackmesser clean all --apigeeapi -u "$$APIGEE_USER" -p "$$APIGEE_PASS" -o "$_APIGEE_ORG" --quiet
+      fi
     secretEnv:
       - 'APIGEE_USER'
       - 'APIGEE_PASS'
   - name: 'gcr.io/$PROJECT_ID/devrel-pipeline:latest'
     id: 'Run Pipeline'
-    entrypoint: "bash"
-    args:
-      - "-c"
-      - |-
-        max_duration=6960 # cloud build timeout minus 4m
-        if [ -n "$_PR_NUMBER" ]; then
-          FULL_PIPELINE_REQUIRED=$(curl "https://api.github.com/repos/$_REPO_GH_ISSUE/issues/$_PR_NUMBER" | jq '.body |= ascii_downcase | .body | contains("[x] pr requires full pipeline run")' )
-          PROJECTS=$(list-repo-changes.sh)
-          if [ "$$FULL_PIPELINE_REQUIRED" = "true" ]; then
-            echo "Running Full Pipeline as required in the PR"
-            timeout "$$max_duration" run-pipelines.sh || true
-          elif [ -z "$$PROJECTS"]; then
-            echo "TOTAL PIPELINE (no change);pass;0" > ./pipeline-result.txt
-          else
-            echo "PR includes changes in $$PROJECTS"
-            timeout "$$max_duration" run-pipelines.sh "$$PROJECTS" || true
-          fi
-        elif [ "$_CI_PROJECT" = "all" ]; then
+    script: |
+      #!/usr/bin/env bash
+      max_duration=$(($_TIMEOUT-240))
+      echo "Running pipeline with timeout $$max_duration"
+      if [ -n "$_PR_NUMBER" ]; then
+        FULL_PIPELINE_REQUIRED=$(curl "https://api.github.com/repos/$_REPO_GH_ISSUE/issues/$_PR_NUMBER" | jq '.body |= ascii_downcase | .body | contains("[x] pr requires full pipeline run")' )
+        PROJECTS=$(list-repo-changes.sh)
+        if [ "$$FULL_PIPELINE_REQUIRED" = "true" ]; then
+          echo "Running Full Pipeline as required in the PR"
           timeout "$$max_duration" run-pipelines.sh || true
+        elif [ -z "$$PROJECTS"]; then
+          echo "TOTAL PIPELINE (no change);pass;0" > ./pipeline-result.txt
         else
-          timeout "$$max_duration" run-pipelines.sh "$_CI_PROJECT" || true
+          echo "PR includes changes in $$PROJECTS"
+          timeout "$$max_duration" run-pipelines.sh "$$PROJECTS" || true
         fi
+      elif [ "$_CI_PROJECT" = "all" ]; then
+        timeout "$$max_duration" run-pipelines.sh || true
+      else
+        timeout "$$max_duration" run-pipelines.sh "$_CI_PROJECT" || true
+      fi
 
-        if [ ! -f ./pipeline-result.txt ]; then
-          echo "No Results Reported;fail;N/A" > ./pipeline-result.txt;
-        elif ! grep -qF "TOTAL PIPELINE" ./pipeline-result.txt; then
-          echo "Pipeline Timeout;fail;[max duration]" >> ./pipeline-result.txt;
-        fi
+      if [ ! -f ./pipeline-result.txt ]; then
+        echo "No Results Reported;fail;N/A" > ./pipeline-result.txt;
+      elif ! grep -qF "TOTAL PIPELINE" ./pipeline-result.txt; then
+        echo "Pipeline Timeout;fail;[max duration]" >> ./pipeline-result.txt;
+      fi
     env:
       - 'APIGEE_ENV=$_APIGEE_ENV'
       - 'APIGEE_ORG=$_APIGEE_ORG'
@@ -100,18 +93,14 @@ steps:
       - 'APIGEE_PASS'
   - name: 'gcr.io/$PROJECT_ID/devrel-pipeline:latest'
     id: 'Write pipeline results to cloud logging'
-    entrypoint: "bash"
-    args:
-      - "-c"
-      - |-
-        cat ./pipeline-result.txt | cloud-logging.sh
+    script: |
+      #!/usr/bin/env bash
+      cat ./pipeline-result.txt | cloud-logging.sh
   - name: 'gcr.io/$PROJECT_ID/devrel-pipeline:latest'
     id: 'Create GH Comment or Issue'
-    entrypoint: "bash"
-    args:
-      - "-c"
-      - |-
-        cat ./pipeline-result.txt | github-api.sh
+    script: |
+      #!/usr/bin/env bash
+      cat ./pipeline-result.txt | github-api.sh
     env:
       - 'BUILD_ID=$BUILD_ID'
       - 'PROJECT_ID=$PROJECT_ID'
@@ -124,11 +113,9 @@ steps:
       - 'GITHUB_TOKEN'
   - name: 'gcr.io/$PROJECT_ID/devrel-pipeline:latest'
     id: 'Explicitly Fail'
-    entrypoint: "bash"
-    args:
-      - "-c"
-      - |-
-        ! grep -q "fail" ./pipeline-result.txt
+    script: |
+      #!/usr/bin/env bash
+      ! grep -q "fail" ./pipeline-result.txt
 availableSecrets:
   secretManager:
     - versionName: projects/$PROJECT_ID/secrets/devrel_apigee_pass/versions/latest
@@ -140,7 +127,7 @@ availableSecrets:
 options:
   machineType: 'E2_HIGHCPU_8'
   logging: GCS_ONLY
-timeout: 7200s # 120min (needs to be updated with max_duration of pipeline)
+timeout: 7200s
 images: ['gcr.io/$PROJECT_ID/devrel-pipeline:latest']
 substitutions:
   _APIGEE_ORG: my-org
@@ -156,4 +143,5 @@ substitutions:
   _REPO_GH_ISSUE: "apigee/devrel"
   _GH_BOT_NAME: "apigee-devrel-bot"
   _RUN_TYPE: "unknown"
+  _TIMEOUT: "7200" #2h
   #_PR_NUMBER: "" # automatically set for PRs
